version: '3.8'

services:
  hash:
    build:
      context: .
      dockerfile: Dockerfile.hash
    ports:
      - "5001:5000"  
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

  encode:
    build:
      context: .
      dockerfile: Dockerfile.encode
    ports:
      - "5002:5000"  
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development